# Generated by Django 5.1.7 on 2025-03-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('sinopsis', models.TextField(blank=True, null=True)),
                ('anio_estreno', models.IntegerField(blank=True, null=True)),
                ('duracion', models.IntegerField(blank=True, help_text='Duración en minutos', null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='peliculas/')),
                ('puntuacion', models.FloatField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=200, null=True)),
                ('actores', models.TextField(blank=True, help_text='Lista de actores separados por comas', null=True)),
                ('generos', models.ManyToManyField(related_name='peliculas', to='movie.genero')),
            ],
        ),
    ]
