# Generated by Django 5.1.7 on 2025-03-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='generos',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='generos',
            field=models.CharField(default='Drama', max_length=100),
        ),
    ]
